controller_list:
  - name: fake_Head_controller
    type: $(arg fake_execution_type)
    joints:
      - Head_Vertical_Joint
  - name: fake_Left_Leg_controller
    type: $(arg fake_execution_type)
    joints:
      - Left_Rot_Hip_Link
      - Left_Hip_Joint
      - Left_Thigh_Joint
      - Left_Calf_Joint
  - name: fake_Left_Shoulder_controller
    type: $(arg fake_execution_type)
    joints:
      - Left_Upper_Shoulder_Motor_Link
      - Left_Mid_Shoulder_Motor_Joint
      - Left_Lower_Shoulder_Motor_Joint
  - name: fake_Right_Leg_controller
    type: $(arg fake_execution_type)
    joints:
      - Right_Rot_Hip_Link
      - Right_Hip_Joint
      - Right_Thigh_Joint
      - Right_Calf_Joint
  - name: fake_Right_Shoulder_controller
    type: $(arg fake_execution_type)
    joints:
      - Right_Upper_Shoulder_Link
      - Right_Mid_Shoulder_Motor_joint
      - Right_Lower_Shoulder_Motor_Joint
initial:  # Define initial robot poses.
  - group: Left_Leg
    pose: 2.Preswing(Toe off)
  - group: Right_Leg
    pose: 1.Heel strike(initial_contact)