# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: Right_Leg
  joint_model_group_pose: 1.Heel_strike(initial_contact)
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Head_Horizontal_Joint
    - Head_Vertical_Joint
    - Left_Hip_Joint
    - Left_Thigh_joint
    - Left_Calf_Joint
    - Left_foot_Joint
    - Left_Upper_Shoulder_Joint
    - Left_Mid_Shoulder_Joint
    - Left_Lower_Shoulder_Joint
    - Right_Hip_Joint
    - Right_Thigh_Joint
    - Right_Calf_Joint
    - Right_Foot_Joint
    - Right_Upper_Shoulder_Joint
    - Right_Mid_Shoulder_Joint
    - Right_Lower_Shoulder_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []